### PR TITLE
Created 3-row column layout in HTML using Bootstrap

### PR DESCRIPTION
**Pull request by packleader206**
Created 3-row column layout in HTML using Bootstrap layout.  Left the original empty Divs of "food" "dinner-table" and "instructions" in tact as empty Div's.  These three empty Divs are inside of the Bootstrap container/wrapper at the very bottom.

### CODE REVIEW

**Review by nholdsworth — CHANGES_REQUESTED** [review]
So at least from my understanding of the code.  The food div should go in the recipe display div, the dinner table div and the instructions div should go inside of the food div.  That way all that info displays there and then all the logic hopefully still does what it was meant to do ( I think it should no problem)...

**Review by Heidijvr — COMMENTED** [review]
Hi Nate, you are quite right, The Food div and its children should go into the recipeDisplay. I did not think to mention that when I asked Al to create the three columns. My mistake

**Review by Heidijvr — APPROVED** [review]
Hi Nate, by removing the food div from the dinner-table id and the form, the search box moves to under the bottom of the lowest image. I feel that this is not very user friendly. What do you think?

**Comment by packleader206** [comment]
If you want to display in columns, we will eventually need the code set up in this row/col structure (with the corresponding id's of course).  I cancelled this pull request because it was a merge conflict with Nate's index.html.

**Comment by packleader206** [comment]
Saving this code here in case we need it.

<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <form id="recipe-request">
                <label for="ingredient-input"> What's in the fridge? </label>
                <input type="text" id="ingredient-input">
                <br>
                
                <input id="find-recipes" type="submit" value="Find my recipes">
            </form>
        </div>
    </div>

    <div class="row">
        <div id="food" class="col-4 text-center">
            <h3>Food Recipe</h3>
            <div id="dinner-table"></div>
            <div id="instructions"></div>
        </div>
    
        <div id="wine-pairing" class="col-4 text-center">
            <h3>Wine-Pairing</h3>    
        </div>
    
        <div id="movies" class="col-4 text-center">
            <h3>Suggested Movies</h3>

            <form>
                <label for="movieGenres"> Movie Genres </label>
                <select class="custom-select" id="movieGenres">
                    <option value="18">Drama</option>
                    <option value="28">Action</option>
                    <option value="35">Comedy</option>
                    <option value="10749">Romance</option>
                    <option value="878">Science Ficton</option>
                </select>
            </form>
        
            <div id="movieTable"></div>
        </div>
    </div>>
</div>

**Pull request closed without merging**
