### PR TITLE
Clear search results and search input before displaying next results

### PR DESCRIPTION
**Pull request by Heidijvr**

### CODE REVIEW

**Review by packleader206 — APPROVED** [review]

**Comment by xoamara** [comment]
@Heidijvr the code you changed from prepend to append now pushes the data below the input box.  Nate had the div for recipes specified above the input box.  If that is what you guys want for structure please confirm @nholdsworth @packleader206.

**Comment by xoamara** [comment]
I'll just approve this and if it ends up the data should be pushed to the top it's an easy fix.

**Review by xoamara — APPROVED** [review]
If the data is supposed to be pushed to the top per the previous div we can reverse the append.

**Comment by Heidijvr** [comment]
> @Heidijvr the code you changed from prepend to append now pushes the data below the input box. Nate had the div for recipes specified above the input box. If that is what you guys want for structure please confirm @nholdsworth @packleader206.

The output is still above the input box because the input box in the search results are no longer in the same div, regardless of append/prepend

**Comment by nholdsworth** [comment]
Hey guys, I put zero thought into the layout, i just threw a div on the page, definitely not because i preferred it that way, it was a slapdash decision

**Pull request merged**
